# -*- coding: utf-8 -*-
"""product.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Gg7y-RILePogo8ynrs1yglwJF4nnvDW
"""

def product(input):
  output = []
  prod = 1
  for i in input:
    for j in input:
      if i == j:
        continue
      prod *= j
    output.append(prod)
    prod = 1
  return output

input = [1, 2, 3, 4, 5]
print(product(input))

